[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
lockdafuckin = "DaAEZvCbrdJ7WADHrmtPSY2rmW6R4c5iZ43PsfxVabYy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
